name: Calculate and Update README

run-name: Calculate and Update README by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      depreciable_item_name:
        description: 'Depreciable item name'
        required: true
      num1:
        description: 'First number'
        required: true
      num2:
        description: 'Second number'
        required: true

jobs:
  calculate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Perform calculation
        id: calculate
        run: |
          total_initial_costs = "0"
          # loop over items
          depreciable_item_name = "Men's socks"
          depreciable_item_cost = "$10"
          total_initial_costs = total_initial_costs + depreciable_item_cost
          # end loop
          total_annual_depreciation = "0"
          # loop over items
          depreciable_item_lifespan_in_years = "1"
          depreciable_item_annual_depreciation = depreciable_item_cost / depreciable_item_lifespan_in_years
          total_annual_depreciation = total_annual_depreciation + depreciable_item_annual_depreciation
          # end loop
          daily_depreciation_cost = total_annual_depreciation / 360
          # result=$(( ${{ github.event.inputs.num1 }} + ${{ github.event.inputs.num2 }} ))
          result=daily_depreciation_cost
          echo "result=$result" >> $GITHUB_ENV

      - name: Update README.md
        run: |
          #echo "The result of ${{ github.event.inputs.num1 }} + ${{ github.event.inputs.num2 }} is ${{ env.result }}." > README.md
          echo "The daily depreciation cost of ${{ github.event.inputs.depreciable_item_name }} is ${{ env.result }}." > README.md
          git config --local user.email "wvanheemstra@icloud.com"
          git config --local user.name "Willem van Heemstra"
          git add README.md
          git commit -m "Update README with calculation result"
          git push
